### PR TITLE
Upgrade to fop 2.1

### PR DESCRIPTION
**Pull request by rahmanusta**
Hi @mojavelinux, Could you please review changes for upgrading to fop 2.1 ?

### CODE REVIEW

**Comment by mojavelinux** [comment]
I tested the upgrade the upgrade of fop to 2.1 and everything seems to work fine. However, you also removed the following two dependencies:

* runtime 'xml-resolver:xml-resolver:1.2'
* runtime 'net.sf.xslthl:xslthl:2.1.0'

These should be restored because they are still needed. xml-resolver allows fopub to work offline. Otherwise, the XML parser tries to reach out to the internet to resolve DTD files (which it should never do). xslthl provides syntax highlighting of source blocks. Both seem to work fine with fop 2.1.

Can you also update the version of fop listed in the README (line 350)?

With those three changes made, I think we'll be good to move forward with the upgrade.

**Comment by rahmanusta** [comment]
You have a point @mojavelinux. I reverted the lines related to 'xml-resolver:xml-resolver:1.2' and 'net.sf.xslthl:xslthl:2.1.0' back. 

What the new version should be ? Do we follow up fop version 2.1.0-SNAPSHOT ?

Thanks

**Comment by mojavelinux** [comment]
You mean the version of fop? If so, I think we should use a stable release, so 2.1. As soon as you add that to the README (which currently says 1.1), then I think we're good to merge.

**Comment by rahmanusta** [comment]
Ah okay, I've updated the line 350 with version 2.1

**Comment by mojavelinux** [comment]
Perfect! Let's merge this!

**Pull request merged**
