### PR TITLE
resolves #92 add support for generating XHTML

### LINKED ISSUE #92: Feature request: add a switch to generate html
As the layout description is generic, it should no be too difficult to render something nice into html.

This would be very useful for people like me, who use `asciidoctor-fopub` in their docbook5 toolchain.

### PR DESCRIPTION
**Pull request by mojavelinux**

### CODE REVIEW

**Comment by getreu** [comment]
I tested you PR and it works nicely. Thank you! 
For me this is a read added value, because I do not have to maintain 2 different toolchains any more.

**Comment by mojavelinux** [comment]
I've given you access to this repository. If you accept, you can merge at will.

**Comment by mojavelinux** [comment]
@getreu Did you accept the invite yet?

**Comment by mojavelinux** [comment]
Don't worry, it's GitHub's fault. They have a terrible workflow for this. That's why I asked.

Here's the link: https://github.com/asciidoctor Look for the invitation banner.

**Comment by mojavelinux** [comment]
I just enabled branch protection on the repo, so you'll need to approve the PR in order to merge it.

**Comment by mojavelinux** [comment]
:+1:

**Comment by andrewcarver** [comment]
Thanks for this enhancement, which seems very significant--in the way of making fopub more of an equivalent to a2x. 
Could someone tell me, also, whether the README has been updated to reflect this new facility? I do see one reference to 'xhtml' there, in the (brief) explanation of the -f option flag; but is that explanation new, and adequate for this new facility, or is it old, and obsolete? Many thanks! (If I need to open an issue, I'll of course do that!)

**Comment by andrewcarver** [comment]
Ah--I see it is [a new addition as of Oct. 27.](https://github.com/asciidoctor/asciidoctor-fopub/commit/62f46874a399e335254091f2d6f9446ae37425dd)
So I'll assume it explains all we need to do, to use fopub to generate xhtml (although it seemed to me the Issue 92 discussion portrayed it as an action more complicated than just using this flag...?)

**Comment by andrewcarver** [comment]
Oh, I guess the procedure-listing I was thinking of, was a procedure for doing this modification to fopub! So, I guess-- never mind! (Thanks again.)

**Comment by mojavelinux** [comment]
There's a brief mention of it in the README here:

https://github.com/asciidoctor/asciidoctor-fopub#fopub-option-flags

If you think more documentation is needed, please feel free to submit a docs update.

**Pull request merged**
