### PR TITLE
add switch to enable hyphenation

### PR DESCRIPTION
**Pull request by mojavelinux**

### CODE REVIEW

**Comment by getreu** [comment]
I merged it into my branch and added some lines of documentation

**Comment by mojavelinux** [comment]
I'll merge this upstream. Would you like to submit the documentation as a pull request?

**Comment by getreu** [comment]
It seems that that all my commits merge automatically into one pull request #62,
some lines of documentation are here: 89243fb9ace8f1ac00b1551c6a8f64fa3da73dd1

**Comment by mojavelinux** [comment]
That's happening because you are sending a pull request from master. You should always sent a pull request from a branch that has only the changes for a single issue. It's really hard to manage a pull request that has many changes.

**Comment by getreu** [comment]
> That's happening because you are sending a pull request from master. You should always sent a pull request from a branch 
I did not know. Thank you.

> that has only the changes for a single issue. It's really hard to manage a pull request that has many changes.
Yes, every commit treats only one issue. But I think the changed lines are sometimes overlapping. So the order matters. I synchronized successfully with your master-branch.

**Comment by mojavelinux** [comment]
The lines overlap because you aren't using branches. One pull request == one branch. Then, all changes stay isolated.

**Pull request merged**
